telegram:
  api_id: 20295350
  api_hash: "805a0a86f3b382d904617d0a2fd4fb6f"
  token: "6590037718:AAFdlILFHw0SOrhppEHYC3aEU0Fk2W4HQDQ"
  lang_code: !!str "en"
  max_upload_tasks: 5
  url_validation_regexes:
    - "^http(s)?:\\/\\/.+$"
  allowed_users:  # Multiple users/groups are allowed.
    - id: -1001997077520  # User or group ID.
      is_admin: !!bool True
      send_startup_message: !!bool True
      download_media_type: "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool True
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool True
        forward_group_id: -1001997077520  # Group or channel ID.
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool True
          include_link: !!bool True
          include_size: !!bool True
  api:
    upload_video_file: !!bool True
    upload_video_max_file_size: 2147483648
    upload_to_chat_ids:  # User, group or channel IDs.
      - 22222222222
      - -33333333333
    silent: !!bool False
    video_caption:
      include_title: !!bool True
      include_filename: !!bool True
      include_link: !!bool True
      include_size: !!bool True
ytdlp:
  version_check_enabled: !!bool True
  version_check_interval: 86400
  notify_users_on_new_version: !!bool True
